### PR TITLE
[10] TracingCommandGateway clean up

### LINKED ISSUE #10: TracingCommandGateway clean up suggestions
The private `sendWithSpan` method uses a wrong parameter order for the `SpanConsumer` functional interface.
Specifically, I am talking about the consumer parameter, where parent and child places are mixed

Also, there is no need for passing `Tracer` instance there since it's a field.

### PR DESCRIPTION
**Pull request by lfgcampos**
I've cleaned up `TracingCommandGateway` as suggested on #10 (fixed the mixed parameter ordering and remove tracer since it is not needed).
Also did a general code formation based on AxonIQ standards.

The changes are separated in 2 commits aiming to make the review easier.

This PR closes #10.

### CODE REVIEW

File: tracing/src/main/java/org/axonframework/extensions/tracing/SpanUtils.java [hunk 1]
```diff
@@ -3,14 +3,14 @@
 import io.opentracing.Tracer;
 import org.axonframework.commandhandling.CommandMessage;
 import org.axonframework.eventhandling.DomainEventMessage;
-import org.axonframework.eventhandling.EventMessage;
 import org.axonframework.messaging.Message;
 import org.axonframework.queryhandling.QueryMessage;
 
 /**
  * Utility class providing methods useful for attaching information to Spans
  */
```
Comment (smcvb) [inline tracing/src/main/java/org/axonframework/extensions/tracing/SpanUtils.java:11]: Nit: Adding the `since` and `author` tags would be nice too whilst you're at it.

Comment (lfgcampos) [reply tracing/src/main/java/org/axonframework/extensions/tracing/SpanUtils.java:11]: Since the one I really touched is `TracingCommandGateway`, I will add it there.
